# Generated by Django 5.1.3 on 2024-11-07 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_cart_cartitem_cart_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart_id',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_id',
            new_name='product',
        ),
    ]
